gplus_loc = '../networks/gplus_combined.txt'
twitter_loc = '../networks/twitter_combined.txt'
fb_loc = '../networks/facebook_combined.txt'
musea_DE_loc = '../networks/musae_DE_edges.csv'
musea_FR_loc = '../networks/musae_FR_edges.csv'